User can view the current days logs | Richard Watanabe
Richard-Watanabe/final-project pull request #13
Opened 2021-09-10 23:35 UTC by Richard-Watanabe

https://user-images.githubusercontent.com/85139853/132927812-9388203b-c405-404c-873d-752fc3b72ba1.mp4

2021-09-10 23:58 UTC, thebearingedge requested changes

2021-09-10 23:58 UTC, thebearingedge commented on client/pages/category-list.jsx
> +    window.location = 'http://localhost:3000/';
we want to avoid doing this as it completely reloads the whole page. You need to use `history.push()` to tell React Router to go back to the root url once the fetch actually completes; it's asynchronous. Check `this.props.history`

2021-09-10 23:58 UTC, thebearingedge commented on client/app.jsx
> +              <Home logs={this.state.logs} />
Instead of fetching the logs in App, fetch them in Home.

2021-09-10 23:58 UTC, thebearingedge commented on client/pages/home.jsx
> +            <button className="btn btn-small btn-outline-success plus text-center">+</button>
Instead of putting a button inside your link, try just styling the link with these classes.

2021-09-10 23:58 UTC, thebearingedge commented on client/pages/log-list.jsx
> +                <span className='margin-lr'>{log.content}:</span>
This is a ton of duplication. Try defining a component  for LogItemIcon that takes the content as a prop and returns the correct icon element.

2021-09-10 23:58 UTC, thebearingedge commented on server/public/styles.css
> +}
this is already how anchors work.

2021-09-11 04:48 UTC, Richard-Watanabe commented
https://user-images.githubusercontent.com/85139853/132936591-126c6fb6-cf35-4c5e-a066-df056027653b.mp4

2021-09-11 15:05 UTC, thebearingedge approved these changes

2021-09-11 15:05 UTC, thebearingedge commented on client/pages/log-item-icon.jsx
> +  }
You can remove the constructor. Refer to `this.props` to determine your className instead of `this.state`.

2021-09-11 20:21 UTC, merged