User can sign into their account | Richard Watanabe
Richard-Watanabe/final-project pull request #16
Opened 2021-09-16 22:32 UTC by Richard-Watanabe

https://user-images.githubusercontent.com/85139853/133694008-ec240d69-23a9-47a7-b1cb-a666d8feafac.mp4

2021-09-16 22:55 UTC, thebearingedge requested changes

2021-09-16 22:55 UTC, thebearingedge commented on client/lib/parse-route.js
> +}
This file shouldn't be necessary when using React Router.

2021-09-16 22:55 UTC, thebearingedge commented on client/pages/app-drawer.jsx
> +              Log Out</a>
Since this anchor doesn't actually link to anything, it'd be better as a customized button. It should _look_ like how it does now, but semantically `<a>` just isn't accurate.

2021-09-16 22:55 UTC, thebearingedge commented on client/pages/home.jsx
> +    // if (!this.context.user) return <Redirect to="sign-in" />;
### 🚓 

commented out code

2021-09-16 22:55 UTC, thebearingedge commented on client/pages/sign-in-form.jsx
> +          window.location.pathname = '/';
Try to use `this.props.history.push()` or `this.props.history.replace()` from React Router instead of changing the pathname.

2021-09-16 22:55 UTC, thebearingedge commented on client/pages/sign-in.jsx
> +// import Redirect from './redirect';
### 👮

2021-09-17 04:55 UTC, Richard-Watanabe commented
https://user-images.githubusercontent.com/85139853/133726773-5c2b9b05-5a4f-4d7c-a5af-2ad63dec6919.mp4

2021-09-18 00:13 UTC, Richard-Watanabe commented
https://user-images.githubusercontent.com/85139853/133865199-d1a8fce5-7052-4153-8ed9-92b91f1e5c1a.mp4

2021-09-18 00:24 UTC, thebearingedge approved these changes

2021-09-18 00:29 UTC, merged